### ISSUE TITLE
Two new metrics not covered by analyticConfigurations

### ISSUE THREAD

**Issue by lbliii** [netuitive-community-packages/netuitive-packages-linux-mysql#10]
Looking at https://github.com/Netuitive/omnibus-netuitive-agent/issues/42 and noticed those two (mysql.Com_show_slave_hosts, mysql.Seconds_Behind_Master) aren't in either of the analyticConfigurations files. Was wondering if they need to be included?

**Comment by rclagett** [comment]
@lbliii They might need to be included when the metrics are removed from the blacklist which hasn't been done yet. Netuitive/omnibus-netuitive-agent#42 is still an open issue.

**Comment by rclagett** [comment]
OBE
